#!/usr/bin/with-contenv bash

# Set the Node.js path to find globally installed modules
export NODE_PATH=/usr/lib/node_modules

# Start the Node.js application
# Start the Node.js application as the 'nobody' user for security
exec s6-setuidgid nobody node /app/server.js
