#!/command/with-contenv bash
# ==============================================================================
# Home Assistant Add-on: WhoRang - Nginx Service
# ==============================================================================

echo "Starting Nginx..."

# Start nginx in the foreground
exec nginx -g "daemon off;"
